# Exmaple search result.
#
# [[search_result]]
# name = "This is the article name. Use the full, spelled-out name of the item.""
# shortname = ["This should contain any common shorthands or abbreviations.", "Multiple, if needed."]
# categories = ["If the result should be returned in a search for a category, put it here.", "Multiple, if needed."]
# ext_links = ["[Google](https://google.com)", "[Example](http://example.com)"]
# text = """ \
# This is the body text of the article. \
# Make sure you explain anything that could be helpful. \
# This also gets searched for search terms, but counts a lot less than the name and shortnames. \
# """

categories = [
    "Awesome Peoople"
]

[[search_result]]
name = "Kali Liada"
shortname = ["Kali", "Marz"]
categories = ["Awesome People"]
ext_links = ["[Example Link](http://example.com"]
text = """ \
This is some text. \
About the search result. \
Hopefully its useful. \
"""

[[search_result]]
name = "Nori Durnin"
shortname = ["Nori"]
categories = ["Awesome People"]
ext_links = ["[Google](https://google.com"]
text = """ \
This is also some text. \
With different stuff in it. \
Yup. \
"""